name: Typedoc

on:
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git branch -f docs
      - run: npm i
      - run: npm run docs
      - run: cp -r docs /tmp/docs
      - run: rm -rf *
      - run: cp -r /tmp/docs/* .
      - run: git add .
      - run: git commit -m "Automated doc gen"
      - run: git push -f origin docs
